name:                advent2019
version:             0.1.0.0
github:              "carlfish/advent2019"
license:             BSD3
author:              "Charles Miller"
maintainer:          "cmiller@pastiche.org"
copyright:           "2019 Charles Miller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent2019#readme>

dependencies:
- array
- attoparsec
- base >= 4.7 && < 5
- bytestring
- mtl
- text

library:
  source-dirs: src
